disabled_rules:
- trailing_whitespace
- shorthand_operator
- todo
opt_in_rules:
- empty_count
- empty_string
- toggle_bool
- weak_delegate
- operator_usage_whitespace
excluded:
- Pods
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 50
    error: 100
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 100
    error: 150
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
